# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26a4bd938faf1ca50b8e4c8595b61feac78949d500cd80f23657177362908f79954f9a640c11611211adf65e50b49ec1194a0ae06695650d2ed52ce480d085ed

test:
  secret_key_base: 645ac6916edc916d30e83518b5de63d756303bc80851d4f362dfd8a3a0549ba9c33d0e78b112b151fb06d430937c521e511b12b7584796512386977406f957e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
